name: Terraform Destroy
on:
  workflow_dispatch:

env:
  TF_ROOT: terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    env:
      OS_CLOUD: vkcs
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Create clouds.yaml
        run: |
          mkdir -p ~/.config/openstack
          echo "$CLOUDS_YAML" > ~/.config/openstack/clouds.yaml
        env:
          CLOUDS_YAML: ${{ secrets.CLOUDS_YAML }}
      - run: terraform init
        working-directory: ${{ env.TF_ROOT }}
      - run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_ROOT }}